# permissions for end users to edit mybooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mybook-editor-role
rules:
- apiGroups:
  - batch.my.domain
  resources:
  - mybooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.my.domain
  resources:
  - mybooks/status
  verbs:
  - get
