# permissions for end users to view mybooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mybook-viewer-role
rules:
- apiGroups:
  - batch.my.domain
  resources:
  - mybooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.my.domain
  resources:
  - mybooks/status
  verbs:
  - get
